### ISSUE TITLE
Section option `titleSeparator` won't allow KQL queries

### ISSUE THREAD

**Issue by dennisbaum** [johannschopplich/kirby-serp-preview#1]
Hi johann, `titleSeparator: "{{ site.metaTitle.value }}"`  wont render? 
<img width="188" alt="image" src="https://github.com/johannschopplich/kirby-serp-preview/assets/562826/a462046e-3c3e-4a72-a39e-3881ea40438e">

**Comment by johannschopplich** [comment]
Hi Dennis! 😉 

The `titleSeparator` section property is only used as the connecting part between the page title and site title. It doesn't support the query syntax. What do you try to achieve here, what's your bluepring? 🙂

**Comment by dennisbaum** [comment]
I would like to add a `Meta-Seperator-Field` to site, so the Customer could chosse, what the seperator should be.
Same for the site Titel. Then in my Blueprint, i would love to access them by the query syntax:

<img width="308" alt="image" src="https://github.com/johannschopplich/kirby-serp-preview/assets/562826/de385700-d8b0-49ff-a3c8-8f02fe446aa0">

```yml
siteTitle: "{{ site.metaTitle.value }}"
titleSeparator: "{{ site.metaSeperator.value }}"
...
```
