### ISSUE TITLE
KQL queries in faviconUrl

### ISSUE THREAD

**Issue by carstengrimm** [johannschopplich/kirby-serp-preview#3]
testing out the serp preview section i notice that i can't use KQL to use the 

```"{{ site.url }}"/path/to/favicon.ico ```

it's not really important just mentioning

**Comment by johannschopplich** [comment]
Why do you need the site URL for the favicon, isn't the absolute path `/path/to/favicon.ico` sufficient?

**Comment by johannschopplich** [comment]
Thanks for the feedback!

**Comment by carstengrimm** [comment]
> Why do you need the site URL for the favicon, isn't the absolute path `/path/to/favicon.ico` sufficient?

i am only developing locally. and using e.g. 

```
/path/to/favicon.ico 

```
kirby panel does not seem to follow the root path so i would have to hardcode... (it may also just be a misconfiguration from me...)

``` 
/localdemo/assets/icon/favicon.ico
```
which may always change. just thinking it's more handy to have the flexibility for site.url
