### ISSUE TITLE
Custom title override 

### ISSUE THREAD

**Issue by grommasdietz** [johannschopplich/kirby-serp-preview#6]
The plugin currently constructs the title like `currentContent[titleContentKey] || [panel.view.title, titleSeparator, siteTitle].join(" ")`. This is fine for most of the pages. However, When using SERP Preview on site or home, it’s may more common to just have the site title instead of the constructed one as a fallback. Should I provide a pull request for that? 

Another or an additional approach could be a titleFallback to get the constructed title (e.g. from a page method) via KQL. It could be integrated like `currentContent[titleContentKey] || titleFallback || [panel.view.title, titleSeparator, siteTitle].join(" ")`. I’m not sure if this would be logically consistent compared to the descriptionFallback, though.

**Comment by johannschopplich** [comment]
Good idea. I think we can unify the naming (while not introducing a breaking change and keeping backwards compatibility in the process). 
What about:
- `defaultDescription` as formerly `descriptionFallback`
- `defaultTitle`

**Comment by grommasdietz** [comment]
Sounds good!

**Comment by grommasdietz** [comment]
Fixed by [`v0.6.0-beta.1`](https://github.com/johannschopplich/kirby-serp-preview/pull/7), without having the site title instead of the constructed one as a fallback, yet.

**Comment by johannschopplich** [comment]
Please let a merged PR auto-close an issue. Otherwise, if a PR is closed without being merged, the issue should stay open. 🙂
