### ISSUE TITLE
Compatibility for Kirby 5

### ISSUE THREAD

**Issue by grommasdietz** [johannschopplich/kirby-serp-preview#8]
During my tests and improvements for Kirby 5 (v5.0-alpha.4), I noticed that the serp section is not rendered anymore. 

The console gives following errors:
```
[Error] TypeError: undefined is not an object (evaluating 'l.getters')
[Error] TypeError: undefined is not an object (evaluating 's.label')
```

Should I investigate further or should we wait for the official release to support Kirby 5?

**Comment by johannschopplich** [comment]
Yes, the latest Kirby 5 alpha introduces breaking changes that plugins like mine need to adapt to.

I will add support for Kirby 5 as soon as Kirby reaches the release candidate phase (as other breaking changes may come).

**Comment by grommasdietz** [comment]
Great! Thanks for having a look and your active support!

**Comment by johannschopplich** [comment]
Since the Kirby 5 beta seems to introduce stabel Panel APIs, I have added support as such. 

I also added the Google dark mode, if Panel theme is set to dark:

![Bildschirmfoto 2024-12-16 um 13 59 17](https://github.com/user-attachments/assets/b7d4d6d4-2b5b-4225-800f-a7b28fa4bce5)
